# Generated by Django 4.0.5 on 2023-05-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campos_relacao', '0003_alter_disciplina_alunos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Morada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('familia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morada', to='campos_relacao.familia')),
            ],
        ),
    ]
