# Generated by Django 4.0.5 on 2023-05-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField()),
                ('pythonanywhere', models.URLField()),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='blog.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Dono',
        ),
    ]
