# Generated by Django 4.0.5 on 2023-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_escritor_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='ecritor',
        ),
        migrations.DeleteModel(
            name='Escritor',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
